import type { Metadata } from "next";
import type { ReactNode } from 'react';

import pNova from "../fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pNova.className}>
        {children}
      </body>
    </html>
  );
}
